server:
  port: 8102
  max-http-header-size: 10000000

spring:
  profiles:
    include: dev
  application:
    name: @pom.artifactId@
  #  rabbitmq:
  #    host: 192.168.204.159
  #    port: 5672
  #    username: admin
  #    password: admin
  rabbitmq:
    #host: 192.168.61.55
#    host: 192.168.204.164
    #host: 172.16.60.35
    host: 192.168.5.85
    port: 5672
    username: admin
    #password: admin
    password: StrongPassword
    # 消息发送至exchange callback
    publisher-confirms: true
    # 消息发送至queue 失败才callback
    publisher-returns: true
    # 消费消息手动删除
    listener:
      simple:
        acknowledge-mode: manual

logging:
  file: /data/logs/ocean/@pom.artifactId@/info/@pom.artifactId@.log