server:
  max-http-header-size: 10000000
  undertow:
    max-http-post-size: 0
    buffer-size: 1024
    direct-buffers: true
  tomcat:
    basedir:  /tmp/tomcat
spring:
  datasource:
    url: jdbc:mysql://10.5.2.93:3306/fantech_imes_v2?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: wuhuan.123
    driverClassName: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 600000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    # 配置一个连接在池中最大生存的时间，单位是毫秒
    maxEvictableIdleTimeMillis: 900000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #  filters: stat,wall,logback
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    host: 10.5.2.92
    #host: 10.182.163.246
    port: 6379
    password: qwe!@#

  rabbitmq:
    host: 10.5.2.93
    port: 5672
    username: admin
    #password: admin
    password: StrongPassword
    # 消息发送至exchange callback
    publisher-confirms: true
    # 消息发送至queue 失败才callback
    publisher-returns: true
    # 消费消息手动删除
    listener:
      simple:
        acknowledge-mode: manual

  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
mybatis:
  config-location: classpath:myBatis-config.xml
  mapper-locations: classpath:mapper/*.xml


#注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    #status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone: http://root:root@10.5.2.92:8761/eureka/
ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 600000
  ReadTimeout: 600000
  MaxConnectionsPerHost: 50
  MaxTotalConnections: 200

tx-lcn:
  client:
    manager-address: 10.5.2.92:8070

feign:
  hystrix:
    enabled: false
  httpclient:
    enabled: true
    connection-timeout: 6000000
  compression:
    request:
      enabled: true
      mime-type: text/html,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

##关闭hystrix 超时
hystrix.command.default.execution.timeout.enabled: false
hystrix.command.default.isolation.thread.timeoutInMilliseconds: 700000

zuul:
  host:
    connect-timeout-millis: 6000000
    socket-timeout-millis: 6000000
    max-per-route-connections: 20
    max-total-connections: 200

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
#提高日志级别为WARN
logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
