server:
  port: 8801
  maxHttpHeaderSize: 10000000

spring:
  profiles:
    active: wanbao
  application:
    name: @pom.artifactId@
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
print:
  ip: 192.168.150.223
  port: 8098

